### ISSUE TITLE
TODO-list

### ISSUE THREAD

**Issue by ravanscafi** [ravanscafi/minesweeper#1]
- [x] Show other mines when game is over.
- [x] Enable service worker
- [x] Allow spotting mines with right click. (and report the wrong and right ones at the end)
- [x] Show a counter with remaining mines.
- [x] Show a timer with elapsed time.
- [x] Show best time
- [x] Allow long press to spot mines on mobile
- [x] Improve the game randomization
- [x] Never start the game with a mine.
- [x] Multiple difficulty levels
- [x] Fix board on mobile devices (for bigger games).
- [x] Improve difficulty buttons.
- [x] Fix display of negative bombs (-05 instead of 0-5)
- [x] Create favicon / sharing screenshot
- [x] Update readme and project screenshot
- [ ] Allow left+right clicks to mark spots (9-grid click).
- [ ] Limit maximum time to 999. (and perhaps bombs too).
- [ ] Allow custom difficulty for board.
- [ ] Improve CSS to make the game fit the screen whenever possible.
- [ ] Add [canvas confetti](https://github.com/catdad/canvas-confetti) when user wins :tada:
